device: "cuda"   
original_image_dir: /workspace/assets/original
reseller_image_dir: /workspace/assets/reseller
output_dir: /workspace/outputs

patch:
  use: true
  width: 1024
  height: 1024

embedding:
  # name should be one of ["dinov2_vitg14", "dinov2_vitl14", "dinov2_vitb14", "dinov2_vits14", 
  #                        "clip_vitl14"]
  name: "dinov2_vitg14" 
  input_size: 518
  output_dir: embedding

faiss:
  index_file: /workspace/outputs/embedding/originals.faiss
  catalog_file: /workspace/outputs/embedding/originals.jsonl
  # 원본 수가 수십~수백 장 이하: Flat(=전수 비교)도 충분히 빠르며 정확도 손실 없음
  # 원본이 수천~수십만 장: IVF(또는 HNSW, IVF-PQ 등)로 가속이 필요 → nlist를 ~sqrt(N)부터 시작해 튜닝 권장. 
  # (예: N=10,000이면 nlist≈100)
  normalize: true
  faiss_nlist: 1
  faiss_nprobe: 1
  topk: 1
  output_dir: scan

thresholds:
  copied: 0.4


