device: "cuda"   

embedding:
  name: "dino_vitl14"   # ["dino_vitl14", "clip_vitl14"]
  embed_dim: 512
  input_size: 224

faiss:
  # 원본 수가 수십~수백 장 이하: Flat(=전수 비교)도 충분히 빠르며 정확도 손실 없음
  # 원본이 수천~수십만 장: IVF(또는 HNSW, IVF-PQ 등)로 가속이 필요 → nlist를 ~sqrt(N)부터 시작해 튜닝 권장. (예: N=10,000이면 nlist≈100)
  normalize: true
  faiss_nlist: 1
  faiss_nprobe: 1
  topk: 1

thresholds:
  copied: 0.4
